name: Deploy
on:
  push:
    branches:
      - main
      - backend
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Maven
        uses: stcarolas/setup-maven@v4.4
        with:
          maven-version: 3.9.2

      - name: Build Application
        run: mvn clean package
