name: Deploy
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Maven
        uses: stcarolas/setup-maven@v4.4
        with:
          maven-version: 3.9.2

      - name: Unit Tests
        run: mvn clean package

      - name: Rename the artifact
        run: cp target/backend-social-network-1.0-SNAPSHOT.jar backend-social-network-${{github.sha}}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: backend-social-network
          path: backend-social-network-${{github.sha}}.jar
