name: Build and Deploy

on:
  push:
    branches:
      - main
      - backend
jobs:
  build-deploy:
    name: Build und Deploy spring boot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
    
      - name: Unit Tests
        run: mvn -B package --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mnv -B package --file pom.xml


