name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build und Deploy spring boot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SDK 17
        uses: actions/setup-java
        with:
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mnv -B package --file pom.xml


