name: Build & Test exclude live

on:
  push:
    branches: [ "main","backend" ]
  pull_request:
    branches: [ "main","backend" ]
jobs:
  build_backend:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Backend
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Marktplatz

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
