name: Build & Test exclude live

on:
  push:
      branches: 
        - '*'
        - '!main'
 

jobs:
  build_backend:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Backend
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Marktplatz

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml

  build_frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout Frontend
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          frontend
          
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.10'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Install Playwright Browsers
      run: |
        cd frontend
        npx playwright install --with-deps

    - name: Build Frontend
      run: |
        cd frontend
        npm run build --if-present

    - name: Run Playwright tests
      run: |
        cd frontend
        npx playwright test

    
